In [30]:
# regression example in tensorflow

# predicting house prices in Boston, Massachussetts

In [31]:
import tensorflow

from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard

import numpy as np
import os

In [32]:
# loading data

(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [33]:
X_train.shape

(404, 13)

In [34]:
X_valid.shape

(102, 13)

In [35]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [36]:
y_train[0]

15.2

In [37]:
# designing neural netwrok architecture

model = Sequential()

# 2 hidden layer architectre, 32 and 16 neurons per layer respectively

# first hidden layer
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

# second hidden layer
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

# output layer
model.add(Dense(1, activation='linear'))

In [38]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 32)                448       
_________________________________________________________________
batch_normalization_4 (Batch (None, 32)                128       
_________________________________________________________________
dense_7 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_5 (Batch (None, 16)                64        
_________________________________________________________________
dropout_2 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
___________________________________________________

In [39]:
# configuring model

model.compile(loss='mean_squared_error', optimizer='nadam')

In [40]:
output_dir = 'model_output/'

In [41]:
run_name = 'regression_drop50'
output_path = output_dir + run_name

In [42]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [43]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', save_weights_only=True)

In [44]:
tensorboard = TensorBoard(log_dir='logs/' + run_name)

In [45]:
# training model

model.fit(X_train, y_train,
    batch_size=8, epochs=32, verbose=1,
    validation_data=(X_valid, y_valid),
    callbacks=[modelcheckpoint, tensorboard]) # val loss below 50 isgood, 40 great

Epoch 1/32
51/51 [==============================] - 2s 46ms/step - loss: 575.1529 - val_loss: 559.6893
Epoch 2/32
51/51 [==============================] - 0s 6ms/step - loss: 559.3876 - val_loss: 584.5728
Epoch 3/32
51/51 [==============================] - 0s 6ms/step - loss: 538.6675 - val_loss: 568.6003
Epoch 4/32
51/51 [==============================] - 0s 6ms/step - loss: 525.2243 - val_loss: 555.7367
Epoch 5/32
51/51 [==============================] - 0s 8ms/step - loss: 506.2468 - val_loss: 527.2971
Epoch 6/32
51/51 [==============================] - 0s 5ms/step - loss: 481.5103 - val_loss: 509.6718
Epoch 7/32
51/51 [==============================] - ETA: 0s - loss: 463.37751/51 [==============================] - 0s 6ms/step - loss: 463.3778 - val_loss: 500.8777
Epoch 8/32
51/51 [==============================] - 0s 7ms/step - loss: 427.8209 - val_loss: 431.9481
Epoch 9/32
51/51 [==============================] - 0s 6ms/step - loss: 397.4454 - val_loss: 377.5272
Epoch 10/32
51/51

In [46]:
# performing inference

model.load_weights(output_path + '/weights.29.hdf5')

In [47]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [48]:
y_valid[42]

14.1

In [49]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[26.655945]], dtype=float32)