In [50]:
# regression example in tensorflow

# predicting house prices in Boston, Massachussetts

In [51]:
import tensorflow

from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard

import numpy as np
import os

In [52]:
# loading data

(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [53]:
X_train.shape

(404, 13)

In [54]:
X_valid.shape

(102, 13)

In [55]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [56]:
y_train[0]

15.2

In [57]:
# designing neural netwrok architecture

model = Sequential()

# 2 hidden layer architectre, 32 and 16 neurons per layer respectively

# first hidden layer
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

# second hidden layer
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

# output layer
model.add(Dense(1, activation='linear'))

In [58]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 32)                448       
_________________________________________________________________
batch_normalization_6 (Batch (None, 32)                128       
_________________________________________________________________
dense_10 (Dense)             (None, 16)                528       
_________________________________________________________________
batch_normalization_7 (Batch (None, 16)                64        
_________________________________________________________________
dropout_3 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
___________________________________________________

In [59]:
# configuring model

model.compile(loss='mean_squared_error', optimizer='nadam')

In [60]:
output_dir = 'model_output/'

In [61]:
run_name = 'regression_drop50'
output_path = output_dir + run_name

In [62]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [63]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', save_weights_only=True)

In [64]:
tensorboard = TensorBoard(log_dir='logs/' + run_name)

In [65]:
# training model

model.fit(X_train, y_train,
    batch_size=8, epochs=32, verbose=1,
    validation_data=(X_valid, y_valid),
    callbacks=[modelcheckpoint, tensorboard]) # val loss below 50 isgood, 40 great

Epoch 1/32
51/51 [==============================] - 3s 59ms/step - loss: 584.8456 - val_loss: 673.8519
Epoch 2/32
51/51 [==============================] - 0s 6ms/step - loss: 569.7605 - val_loss: 653.7142
Epoch 3/32
51/51 [==============================] - 1s 14ms/step - loss: 548.2325 - val_loss: 616.1511
Epoch 4/32
51/51 [==============================] - 0s 5ms/step - loss: 535.7404 - val_loss: 570.6827
Epoch 5/32
51/51 [==============================] - 0s 5ms/step - loss: 511.2082 - val_loss: 511.2424
Epoch 6/32
51/51 [==============================] - 0s 6ms/step - loss: 496.3146 - val_loss: 480.6298
Epoch 7/32
51/51 [==============================] - 0s 6ms/step - loss: 467.9565 - val_loss: 418.8732
Epoch 8/32
51/51 [==============================] - 0s 6ms/step - loss: 438.9442 - val_loss: 381.4427
Epoch 9/32
51/51 [==============================] - 0s 5ms/step - loss: 419.4967 - val_loss: 388.9888
Epoch 10/32
51/51 [==============================] - 0s 5ms/step - loss: 391.283

In [66]:
# performing inference

model.load_weights(output_path + '/weights.29.hdf5')

In [67]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [68]:
y_valid[42]

14.1

In [69]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[15.964156]], dtype=float32)