In [ ]:
# regression example in tensorflow

# predicting house prices in Boston, Massachussetts

In [21]:
import tensorflow

from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint

import numpy as np
import os

In [2]:
# loading data

(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57344/57026 [==============================] - 0s 1us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

In [7]:
# designing neural netwrok architecture

model = Sequential()

# 2 hidden layer architectre, 32 and 16 neurons per layer respectively

# first hidden layer
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

# second hidden layer
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# output layer
model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                448       
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
dropout (Dropout)            (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
_____________________________________________________

In [9]:
# configuring model

model.compile(loss='mean_squared_error', optimizer='nadam')

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', save_weights_only=True)

In [14]:
# training model

model.fit(X_train, y_train,
    batch_size=8, epochs=32, verbose=1,
    validation_data=(X_valid, y_valid),
    callbacks=[modelcheckpoint]) # val loss below 50 isgood, 40 great

Epoch 1/32
51/51 [==============================] - 1s 12ms/step - loss: 572.8239 - val_loss: 685.3602
Epoch 2/32
51/51 [==============================] - 0s 7ms/step - loss: 557.3744 - val_loss: 644.0165
Epoch 3/32
51/51 [==============================] - 0s 5ms/step - loss: 537.6340 - val_loss: 604.4788
Epoch 4/32
51/51 [==============================] - 0s 8ms/step - loss: 519.1701 - val_loss: 573.1204
Epoch 5/32
51/51 [==============================] - 0s 7ms/step - loss: 492.9134 - val_loss: 534.3193
Epoch 6/32
51/51 [==============================] - 0s 7ms/step - loss: 465.7969 - val_loss: 485.2360
Epoch 7/32
51/51 [==============================] - 0s 5ms/step - loss: 436.6299 - val_loss: 453.1567
Epoch 8/32
51/51 [==============================] - 0s 5ms/step - loss: 405.9468 - val_loss: 426.8734
Epoch 9/32
51/51 [==============================] - 0s 6ms/step - loss: 361.3004 - val_loss: 392.9182
Epoch 10/32
51/51 [==============================] - 0s 4ms/step - loss: 325.8438

In [16]:
# performing inference

model.load_weights(output_path + '/weights.29.hdf5')

In [17]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [18]:
y_valid[42]

14.1

In [22]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[18.324783]], dtype=float32)